### ISSUE TITLE
App doesn't connect to Spotify API

### ISSUE THREAD

**Issue by joaonmatos** [TitoGrine/Ascoldata#2]
Hey hey! Great initiative!

I was super excited to jump but the app seemed to not load anything. :(

I opened the console and saw a bunch of error messages about cross origin requests to the Spotify API being blocked.

Can you take a look at it?

![Profile](https://user-images.githubusercontent.com/33482573/93382678-5c72e480-f85a-11ea-8472-01a76a3b2698.png)

![Top Listened](https://user-images.githubusercontent.com/33482573/93382455-0dc54a80-f85a-11ea-8953-4aa8e5ca8fd9.png)

![Your Liked Songs](https://user-images.githubusercontent.com/33482573/93382472-11f16800-f85a-11ea-888d-2b77b80ed27d.png)

![Your Playlists](https://user-images.githubusercontent.com/33482573/93382483-16b61c00-f85a-11ea-8140-db3aa708f1da.png)

![Portugal new releases](https://user-images.githubusercontent.com/33482573/93382494-19b10c80-f85a-11ea-97cf-000334a0a159.png)

[console-export-2020-9-16_20-16-19.txt](https://github.com/TitoGrine/Ascoldata/files/5234494/console-export-2020-9-16_20-16-19.txt)

Lots of love <3

**Comment by joaonmatos** [comment]
My suggestion is using your backend to proxy the requests to the spotify api

**Comment by TitoGrine** [comment]
The issue probably resides in an extension you have that blocks requests to the Spotify API.
Disabling the extension for the site should fix it.
Thanks for the feedback though!

**Comment by joaonmatos** [comment]
It does seem that the culprit is the Privacy Badger extension, thnaks for the feedback! However, would you consider looking into procuring an exception for your app?

**Comment by TitoGrine** [comment]
Upon a quick search it seems that requesting an exception isn't a straight forward process. Given the traffic this site generates, I think for the time being it isn't worth investing on it, but that can change in the future. Thanks for the suggestion though!
